In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("student_performance_prediction.csv")

In [3]:
df

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No
...,...,...,...,...,...,...,...
39995,S39996,15.6,93.8,51.4,Yes,Master,No
39996,S39997,11.3,66.4,64.2,No,Doctorate,Yes
39997,S39998,13.1,65.6,38.1,No,Bachelor,No
39998,S39999,14.1,74.9,NaN,Yes,Master,No
39999,S40000,11.8,55.1,68.5,No,Bachelor,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 7 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Student ID                                   40000 non-null  object
 1   Study Hours per Week                         38005 non-null  float64
 2   Attendance Rate                              38008 non-null  float64
 3   Previous Grades                              38006 non-null  float64
 4   Participation in Extracurricular Activities  38000 non-null  object
 5   Parent Education Level                       38000 non-null  object
 6   Passed                                       38000 non-null  object
dtypes: float64(3), object(4)
memory usage: 2.1+ MB

In [5]:
df.shape

(40000, 7)

In [6]:
df.describe()

       Study Hours per Week  Attendance Rate  Previous Grades
count          38005.000000     38008.000000     38006.000000
mean               9.962744        75.276323        65.440107
std                5.031154        20.393418        16.503119
min              -12.300000       -14.300000         8.300000
25%                6.600000        61.600000        55.100000
50%               10.000000        75.300000        65.200000
75%               13.400000        88.800000        75.200000
max               32.400000       150.200000       200.000000

### Fixing Outliers

In [7]:
# study hours cannot be negative 
df.loc[df['Study Hours per Week'] < 0, 'Study Hours per Week'] = np.nan

# attendance between 0-100
df.loc[(df['Attendance Rate'] < 0) | (df['Attendance Rate'] > 100), 'Attendance Rate'] = np.nan

# pervious grades (assuming 0-100 scale)
df.loc[df['Previous Grades'] > 100,' Previous Grades'] = np.nan

In [8]:
# impute numerical column with median
num_col = ['Study Hours per Week', 'Attendance Rate', 'Previous Grades']
for col in num_col:
      df[col] = df[col].fillna(df[col].median())

In [9]:
# impute categorical column with mode
cat_col = ['Participation in Extracurricular Activities', 'Parent Education Level', 'Passed']
for col in cat_col:
      df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
df = df.drop_duplicates()

In [11]:
df.isnull().sum()

Student ID                                         0
Study Hours per Week                               0
Attendance Rate                                    0
Previous Grades                                    0
Participation in Extracurricular Activities        0
Parent Education Level                             0
Passed                                             0
 Previous Grades                               40000
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 8 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Student ID                                   40000 non-null  object
 1   Study Hours per Week                         40000 non-null  float64
 2   Attendance Rate                              40000 non-null  float64
 3   Previous Grades                              40000 non-null  float64
 4   Participation in Extracurricular Activities  40000 non-null  object
 5   Parent Education Level                       40000 non-null  object
 6   Passed                                       40000 non-null  object
 7    Previous Grades                             0 non-null      float64
dtypes: float64(4), object(4)
memory usage: 2.4+ MB

In [13]:
df.to_csv("cleaned_student_performance.csv", index=False)